2017-11-25 01:53:33,931 - DEBUG - Parsing arguments.
2017-11-25 01:53:33,935 - DEBUG - Activated debug logging.
2017-11-25 01:53:33,935 - DEBUG - clean_collections: False
2017-11-25 01:53:33,936 - DEBUG - trade_amount: 0.10
2017-11-25 01:53:33,936 - DEBUG - amount_dynamic: True
2017-11-25 01:53:33,936 - DEBUG - trade_proportion_initial: 0.05
2017-11-25 01:53:33,936 - DEBUG - trade_usdt_max: 1.00
2017-11-25 01:53:33,936 - DEBUG - profit_threshold: 0.05
2017-11-25 01:53:33,937 - DEBUG - loop_time: 20
2017-11-25 01:53:33,937 - DEBUG - loop_dynamic: True
2017-11-25 01:53:33,937 - DEBUG - live_trading: True
2017-11-25 01:53:33,937 - DEBUG - csv_logging: True
2017-11-25 01:53:33,938 - DEBUG - telegram_active: True
2017-11-25 01:53:33,938 - DEBUG - mongo_alt: False
2017-11-25 01:53:33,938 - INFO - Dynamic loop time calculation activated. Base loop time set to 20 seconds.
2017-11-25 01:53:33,938 - INFO - CSV log file path: logs/lorenzbot_log_11252017-015333.csv
2017-11-25 01:53:33,947 - INFO - Using default MongoDB database 'lorenzbot'.
2017-11-25 01:53:33,955 - INFO - No collections found in database. Creating new...
2017-11-25 01:53:34,287 - INFO - Created new collection: 11252017_015333
2017-11-25 01:53:34,288 - INFO - Found Telegram config file.
2017-11-25 01:53:34,310 - DEBUG - telegram_token: 411687950:AAFOIzovAmjDoy_0qJeBfdtzTFkM74BI0Fs
2017-11-25 01:53:34,317 - INFO - Found Poloniex config file.
2017-11-25 01:53:34,338 - WARNING - Live trading ENABLED.
2017-11-25 01:53:34,918 - INFO - Current Maker Fee: 0.0015
2017-11-25 01:53:34,918 - INFO - Current Taker Fee: 0.0025
2017-11-25 01:53:35,269 - INFO - Balance STR:  244.39
2017-11-25 01:53:35,269 - INFO - Balance USDT: 30.34
2017-11-25 01:53:35,283 - INFO - Collection empty. Setting tradable balance remaining to allowed maximum.
2017-11-25 01:53:35,284 - DEBUG - trade_usdt_remaining: 1.00
2017-11-25 01:53:35,284 - INFO - Tradable USDT Remaining: 1.00
2017-11-25 01:53:35,287 - DEBUG - ----[LOOP START]----
2017-11-25 01:53:35,287 - DEBUG - Entering base_price calculation.
2017-11-25 01:53:35,288 - DEBUG - MongoDB collection length: 0
2017-11-25 01:53:35,289 - DEBUG - trade_prop: 0.05000000
2017-11-25 01:53:36,602 - DEBUG - actual: 1.00000000
2017-11-25 01:53:36,603 - DEBUG - book_tot: 0.08
2017-11-25 01:53:36,603 - DEBUG - calc_limit_price() successful within limits (depth=20).
2017-11-25 01:53:36,603 - DEBUG - trade_amount_initial[CALC]: 1.00
2017-11-25 01:53:36,603 - INFO - No trade log found. Making entry buy.
2017-11-25 01:53:36,604 - INFO - Entry trade amount: 1.00000000
2017-11-25 01:53:36,887 - DEBUG - actual: 0.04141109
2017-11-25 01:53:36,887 - DEBUG - book_tot: 3561.76
2017-11-25 01:53:36,887 - DEBUG - actual: 0.04141109
2017-11-25 01:53:36,887 - DEBUG - book_tot: 3561.76
2017-11-25 01:53:36,887 - DEBUG - calc_limit_price() successful within limits (depth=20).
2017-11-25 01:53:36,887 - DEBUG - limit_price: 0.04141109
2017-11-25 01:53:37,409 - DEBUG - [BUY] trade_response: {'orderNumber': '39717815552', 'resultingTrades': [], 'amountUnfilled': '1.00000000'}
2017-11-25 01:53:37,826 - ERROR - Entry buy failed. Exiting.
Traceback (most recent call last):
  File "lorenzbot_telegram.py", line 213, in calc_base
    exec_trade('buy', limit_price, trade_amount_initial)
  File "lorenzbot_telegram.py", line 357, in exec_trade
    order_details = process_trade_response(trade_response, position)
  File "lorenzbot_telegram.py", line 431, in process_trade_response
    order_trades = polo.returnOrderTrades(response['orderNumber'])
  File "/Users/hunterallen/Documents/crypto/lorenzbot/env/lib/python3.6/site-packages/poloniex/__init__.py", line 404, in returnOrderTrades
    'orderNumber': str(orderNumber)})
  File "/Users/hunterallen/Documents/crypto/lorenzbot/env/lib/python3.6/site-packages/poloniex/__init__.py", line 143, in retrying
    return func(*args, **kwargs)
  File "/Users/hunterallen/Documents/crypto/lorenzbot/env/lib/python3.6/site-packages/poloniex/__init__.py", line 203, in __call__
    return self.handleReturned(ret.text)
  File "/Users/hunterallen/Documents/crypto/lorenzbot/env/lib/python3.6/site-packages/poloniex/__init__.py", line 270, in handleReturned
    raise PoloniexError(out['error'])
poloniex.PoloniexError: Order not found, or you are not the person who placed it.
